apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-config
  namespace: flux-system
spec:
  interval: 5m
  path: "./apps/base/external-secrets-config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # Category-based dependency: config depends on infrastructure-operators being ready
  dependsOn:
    - name: infrastructure-operators
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars