---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-operator
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/base/cnpg-operator
  prune: true
  wait: true
  timeout: 15m
  # Category-based dependency: operators depend on infrastructure-core being ready
  dependsOn:
    - name: infrastructure-core