apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 1m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 65.2.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Prometheus configuration
    prometheus:
      prometheusSpec:
        # Storage configuration
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: "local-path"
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
        
        # Resource limits
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "1Gi"
            cpu: "500m"
        
        # Retention policy
        retention: "30d"
        retentionSize: "8GB"
    
    # Grafana configuration
    grafana:
      enabled: true
      adminPassword: "admin123"
      
      # Service configuration
      service:
        type: ClusterIP
        port: 80
      
      # Resource limits
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"
      
      # Persistence
      persistence:
        enabled: true
        storageClassName: "local-path"
        size: 5Gi
    
    # AlertManager configuration
    alertmanager:
      alertmanagerSpec:
        # Storage configuration
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: "local-path"
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 2Gi
        
        # Resource limits
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
    
    # Node Exporter configuration
    nodeExporter:
      enabled: true
    
    # Kube State Metrics configuration
    kubeStateMetrics:
      enabled: true
