apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - externalsecret.yaml
  - externalsecret-grafana-db.yaml
  - helmrelease.yaml
  - ingressroute.yaml
  - servicemonitor-agentic-ai.yaml
  - grafana-dashboard-kagent.yaml
