---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrelease.yaml
  # Temporarily disabled due to webhook timeout
  # - secretstore.yaml
  # - n8n-external-secret.yaml
