---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-postgres-credentials-external
  namespace: n8n
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: localstack-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: n8n-postgres-credentials-from-external
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DATABASE
      remoteRef:
        key: n8n-postgres-credentials
        property: POSTGRES_DATABASE
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: n8n-postgres-credentials
        property: POSTGRES_HOST
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: n8n-postgres-credentials
        property: POSTGRES_PORT
    - secretKey: POSTGRES_USERNAME
      remoteRef:
        key: n8n-postgres-credentials
        property: POSTGRES_USERNAME
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: n8n-postgres-credentials
        property: POSTGRES_PASSWORD
