apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-cnpg-app-secret
  namespace: cnpg-system
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: localstack-secretstore
      kind: ClusterSecretStore
  selector:
    secret:
      name: postgresql-cluster-app
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: cnpg/postgresql-cluster-app/username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: cnpg/postgresql-cluster-app/password
    - match:
        secretKey: host
        remoteRef:
          remoteKey: cnpg/postgresql-cluster-app/host
    - match:
        secretKey: port
        remoteRef:
          remoteKey: cnpg/postgresql-cluster-app/port
    - match:
        secretKey: dbname
        remoteRef:
          remoteKey: cnpg/postgresql-cluster-app/dbname
    - match:
        secretKey: uri
        remoteRef:
          remoteKey: cnpg/postgresql-cluster-app/uri
    - match:
        secretKey: jdbc-uri
        remoteRef:
          remoteKey: cnpg/postgresql-cluster-app/jdbc-uri
