apiVersion: external-secrets.io/v1beta1
kind: PushSecret
metadata:
  name: push-cnpg-app-secret
  namespace: cnpg-system
spec:
  selector:
    secret:
      name: postgresql-cluster-app
  secretStoreRefs:
    - name: localstack-secretstore
      kind: ClusterSecretStore
  data:
    - match:
        secretKey: username
      to:
        secretKey: username
    - match:
        secretKey: password
      to:
        secretKey: password
    - match:
        secretKey: host
      to:
        secretKey: host
    - match:
        secretKey: port
      to:
        secretKey: port
    - match:
        secretKey: dbname
      to:
        secretKey: dbname
