---
apiVersion: v1
kind: Namespace
metadata:
  name: code-tools
  labels:
    app.kubernetes.io/name: code-tools
    app.kubernetes.io/managed-by: flux
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/audit: baseline
