---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-postgres-credentials
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: localstack-secretstore
    kind: ClusterSecretStore
  target:
    name: n8n-postgres-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        POSTGRES_HOST: "{{ .host }}.cnpg-system.svc.cluster.local"
        POSTGRES_PORT: "{{ .port }}"
        POSTGRES_USERNAME: "{{ .username }}"
        POSTGRES_PASSWORD: "{{ .password }}"
        POSTGRES_DATABASE: "n8n"
  data:
    - secretKey: host
      remoteRef:
        key: cnpg/postgresql-cluster-app/host
    - secretKey: port
      remoteRef:
        key: cnpg/postgresql-cluster-app/port
    - secretKey: username
      remoteRef:
        key: cnpg/postgresql-cluster-app/username
    - secretKey: password
      remoteRef:
        key: cnpg/postgresql-cluster-app/password