apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: n8n-helm-chart
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/8gears/n8n-helm-chart
  ref:
    tag: "1.0.10"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/n8n
      version: "1.0.10"
      sourceRef:
        kind: GitRepository
        name: n8n-helm-chart
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # n8n configuration
    n8n:
      # Set the encryption key for n8n
      # encryptionKey: "your-encryption-key-here"

      # Database configuration (optional - uses SQLite by default)
      # database:
      #   type: postgresdb
      #   postgresdb:
      #     host: postgres-service
      #     port: 5432
      #     database: n8n
      #     user: n8n
      #     password: password

    # Ingress configuration
    # ingress:
    #   enabled: true
    #   className: "nginx"
    #   annotations:
    #     cert-manager.io/cluster-issuer: "letsencrypt-prod"
    #   hosts:
    #     - host: n8n.yourdomain.com
    #       paths:
    #         - path: /
    #           pathType: Prefix
    #   tls:
    #     - secretName: n8n-tls
    #       hosts:
    #         - n8n.yourdomain.com

    # Persistence configuration
    persistence:
      enabled: true
      size: 1Gi
      # storageClass: "default"

    # Service configuration
    service:
      type: ClusterIP
      port: 5678

    # Resource limits
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
