apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrelease.yaml

secretGenerator:
  - name: n8n-postgres-credentials
    namespace: n8n
    envs:
      - ../../.env
    options:
      disableNameSuffixHash: true
