apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kagent
resources:
  - agent.yaml
configMapGenerator:
  - name: investigation-agent-prompt
    files:
      - system-message.md
    options:
      disableNameSuffixHash: true
