#!/usr/bin/env python3
"""
inject_nav.py — Merge the generated fleet-infra nav fragment into mkdocs.yml.

Reads the nav.yml fragment produced by render.py (a single top-level list item
whose key matches NAV_SECTION_KEY) and replaces the matching entry inside
the mkdocs.yml "Projects:" nav section.

Usage:
    python3 inject_nav.py --nav-fragment <nav.yml> --mkdocs <mkdocs.yml>

The script is idempotent: running it twice produces the same result.
"""

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml not installed. Run: pip install -r requirements.txt", file=sys.stderr)
    sys.exit(1)

# The key in the generated nav.yml fragment that represents the flux-infra section.
# render.py emits "Flux Infra:" as the top-level key.
NAV_FRAGMENT_KEY = "Flux Infra"

# The key in mkdocs.yml nav → Projects that we want to replace.
# Covers old names ("Fleet Infrastructure", "Fleet Infra") and new names.
NAV_TARGET_KEYS = {"Fleet Infrastructure", "Fleet Infra", "Flux Infrastructure", "Flux Infra"}


def load_yaml(path: Path):
    with open(path) as f:
        return yaml.safe_load(f)


def inject(nav_fragment_path: Path, mkdocs_path: Path) -> None:
    # Load generated fragment — it's a list with one item: {NAV_FRAGMENT_KEY: [...]}
    fragment_list = load_yaml(nav_fragment_path)
    if not isinstance(fragment_list, list) or len(fragment_list) == 0:
        print(f"ERROR: {nav_fragment_path} is empty or not a list", file=sys.stderr)
        sys.exit(1)

    # Find the fleet-infra entry in the fragment
    new_entry = None
    for item in fragment_list:
        if isinstance(item, dict) and NAV_FRAGMENT_KEY in item:
            new_entry = item
            break
    if new_entry is None:
        print(f"ERROR: nav fragment has no '{NAV_FRAGMENT_KEY}' key", file=sys.stderr)
        sys.exit(1)

    # Render the new nav block as YAML with the canonical key name
    new_section_yaml = yaml.dump(
        [{"Flux Infrastructure": new_entry[NAV_FRAGMENT_KEY]}],
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
    )

    # mkdocs.yml may contain !!python/name: tags that safe_load refuses to handle.
    # Use pure text-based block replacement instead.
    mkdocs_raw = mkdocs_path.read_text()
    lines = mkdocs_raw.splitlines(keepends=True)

    # Find the line containing "- Fleet Infrastructure:" or "- Fleet Infra:"
    # and determine its indentation level.
    fleet_line_idx = None
    fleet_indent = None
    for i, line in enumerate(lines):
        stripped = line.strip()
        for key in NAV_TARGET_KEYS:
            if stripped.startswith(f"- {key}:") or stripped == f"- {key}:":
                fleet_line_idx = i
                fleet_indent = len(line) - len(line.lstrip())
                break
        if fleet_line_idx is not None:
            break

    if fleet_line_idx is None:
        print("ERROR: Could not find Fleet Infrastructure nav block in mkdocs.yml", file=sys.stderr)
        sys.exit(1)

    # Find the end of the fleet-infra block: the next line at the SAME or LOWER indent
    # that is not a child of the current block (i.e., same bullet level).
    fleet_end_idx = len(lines)
    for i in range(fleet_line_idx + 1, len(lines)):
        line = lines[i]
        if not line.strip():
            continue  # blank lines are part of the block
        curr_indent = len(line) - len(line.lstrip())
        if curr_indent <= fleet_indent and line.lstrip().startswith("-"):
            fleet_end_idx = i
            break

    # Build replacement lines — indent each line from the YAML dump to match fleet_indent
    indent_str = " " * fleet_indent
    replacement_lines = []
    for raw_line in new_section_yaml.splitlines(keepends=True):
        replacement_lines.append(indent_str + raw_line)

    result_lines = lines[:fleet_line_idx] + replacement_lines + lines[fleet_end_idx:]
    mkdocs_path.write_text("".join(result_lines))
    print(f"  Injected fleet-infra nav into {mkdocs_path}")


def main():
    parser = argparse.ArgumentParser(description="Inject fleet-infra nav fragment into mkdocs.yml")
    parser.add_argument("--nav-fragment", required=True, help="Path to nav.yml generated by render.py")
    parser.add_argument("--mkdocs", required=True, help="Path to target mkdocs.yml")
    args = parser.parse_args()

    nav_fragment_path = Path(args.nav_fragment)
    mkdocs_path = Path(args.mkdocs)

    if not nav_fragment_path.exists():
        print(f"ERROR: nav fragment not found: {nav_fragment_path}", file=sys.stderr)
        sys.exit(1)
    if not mkdocs_path.exists():
        print(f"ERROR: mkdocs.yml not found: {mkdocs_path}", file=sys.stderr)
        sys.exit(1)

    inject(nav_fragment_path, mkdocs_path)


if __name__ == "__main__":
    main()
