---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/base/weave-gitops
  prune: true
  wait: true
  timeout: 5m0s
  # Category-based dependency: monitoring depends on infrastructure-core being ready
  dependsOn:
    - name: infrastructure-core
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
