apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: redis
  namespace: flux-system
spec:
  type: oci
  interval: 5m
  url: oci://registry-1.docker.io/bitnamicharts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system 
spec:
  targetNamespace: redis
  interval: 30m
  chart:
    spec:
      chart: redis
      reconcileStrategy: Revision
      version: "20.3.0"
      sourceRef:
        kind: HelmRepository
        name: redis
        namespace: flux-system
  values:
    # Enable Redis Sentinel architecture
    architecture: replication
    
    # Override default naming
    fullnameOverride: "redis"
    
    # Authentication configuration
    auth:
      enabled: true
      existingSecret: "redis-password"
      existingSecretPasswordKey: "password"

    # Redis Sentinel configuration
    sentinel:
      enabled: true
      masterSet: "mymaster"
      downAfterMilliseconds: 30000
      failoverTimeout: 180000
      parallelSyncs: 1
      
    # Redis Master configuration
    master:
      count: 1
      service:
        type: ClusterIP
        ports:
          redis: 6379
      persistence:
        enabled: true
        size: "8Gi"
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "500m"
        
    # Redis Replica configuration  
    replica:
      replicaCount: 2
      podAntiAffinityPreset: hard
      service:
        type: ClusterIP
        ports:
          redis: 6379
      persistence:
        enabled: true
        size: "8Gi"
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      autoscaling:
        enabled: true
        maxReplicas: 3
        minReplicas: 2
        targetCPU: "80" 
        targetMemory: "80" 
        
    # Metrics configuration (optional)
    metrics:
      enabled: false
      serviceMonitor:
        enabled: true
        interval: 30s