apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base

configMapGenerator:
  - name: cluster-vars
    behavior: merge
    envs:
      - environment.env
    options:
      disableNameSuffixHash: true
    namespace: flux-system