apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cnpg-backup-s3
  namespace: cnpg-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: localstack-secretstore
    kind: ClusterSecretStore
  target:
    name: cnpg-backup-s3
    creationPolicy: Owner
    template:
      data:
        ACCESS_KEY_ID: "{{ .access_key_id }}"
        ACCESS_SECRET_KEY: "{{ .secret_access_key }}"
  data:
    - secretKey: access_key_id  # pragma: allowlist secret
      remoteRef:
        key: cnpg/backup/s3
        property: access_key_id  # pragma: allowlist secret
    - secretKey: secret_access_key  # pragma: allowlist secret
      remoteRef:
        key: cnpg/backup/s3
        property: secret_access_key  # pragma: allowlist secret
