apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pgadmin4
  namespace: flux-system
spec:
  interval: 10m
  timeout: 10m
  retryInterval: 2m
  path: "./apps/base/pgadmin4"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # Category-based dependency: database UI depends on database workloads being ready
  dependsOn:
    - name: database-workloads
  postBuild:
    substitute:
      cluster_name: ${CLUSTER_NAME}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars