---
apiVersion: v1
kind: Namespace
metadata:
  name: node-maintenance
  labels:
    app.kubernetes.io/name: node-maintenance
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
