---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argocd
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 1m
  timeout: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/base/argocd
  prune: true
  wait: true
  dependsOn:
    - name: traefik-config
    - name: external-secrets-config
    - name: redis-sentinel
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: argocd-server
      namespace: argocd
    - apiVersion: apps/v1
      kind: StatefulSet
      name: argocd-application-controller
      namespace: argocd
