apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-vars
  namespace: flux-system
data:
  CLUSTER_NAME: services-amer-dev

  # High Availability Override for Development Testing
  # Override base config to test anti-affinity with minimum HA setup
  TRAEFIK_REPLICA_COUNT: "2"
