#!/bin/bash
set -e

LOCALSTACK_ENDPOINT="http://localhost:4566"

echo "🔐 Initializing CNPG PostgreSQL secrets in LocalStack..."

# Create CNPG PostgreSQL cluster app credentials
# These would normally be auto-generated by CNPG, but we pre-populate them for External Secrets
aws --endpoint-url=$LOCALSTACK_ENDPOINT secretsmanager create-secret \
  --name "cnpg/postgresql-cluster-app/host" \
  --description "PostgreSQL cluster hostname" \
  --secret-string "postgresql-cluster-rw" \
  --region us-east-1 2>/dev/null || \
aws --endpoint-url=$LOCALSTACK_ENDPOINT secretsmanager update-secret \
  --secret-id "cnpg/postgresql-cluster-app/host" \
  --secret-string "postgresql-cluster-rw" \
  --region us-east-1

aws --endpoint-url=$LOCALSTACK_ENDPOINT secretsmanager create-secret \
  --name "cnpg/postgresql-cluster-app/port" \
  --description "PostgreSQL cluster port" \
  --secret-string "5432" \
  --region us-east-1 2>/dev/null || \
aws --endpoint-url=$LOCALSTACK_ENDPOINT secretsmanager update-secret \
  --secret-id "cnpg/postgresql-cluster-app/port" \
  --secret-string "5432" \
  --region us-east-1

aws --endpoint-url=$LOCALSTACK_ENDPOINT secretsmanager create-secret \
  --name "cnpg/postgresql-cluster-app/username" \
  --description "PostgreSQL app username" \
  --secret-string "app" \
  --region us-east-1 2>/dev/null || \
aws --endpoint-url=$LOCALSTACK_ENDPOINT secretsmanager update-secret \
  --secret-id "cnpg/postgresql-cluster-app/username" \
  --secret-string "app" \
  --region us-east-1

aws --endpoint-url=$LOCALSTACK_ENDPOINT secretsmanager create-secret \
  --name "cnpg/postgresql-cluster-app/password" \
  --description "PostgreSQL app password" \
  --secret-string "$(openssl rand -base64 32 | tr -d /=+ | cut -c -16)" \
  --region us-east-1 2>/dev/null || \
aws --endpoint-url=$LOCALSTACK_ENDPOINT secretsmanager update-secret \
  --secret-id "cnpg/postgresql-cluster-app/password" \
  --secret-string "$(openssl rand -base64 32 | tr -d /=+ | cut -c -16)" \
  --region us-east-1

aws --endpoint-url=$LOCALSTACK_ENDPOINT secretsmanager create-secret \
  --name "cnpg/postgresql-cluster-app/dbname" \
  --description "PostgreSQL database name" \
  --secret-string "appdb" \
  --region us-east-1 2>/dev/null || \
aws --endpoint-url=$LOCALSTACK_ENDPOINT secretsmanager update-secret \
  --secret-id "cnpg/postgresql-cluster-app/dbname" \
  --secret-string "appdb" \
  --region us-east-1

aws --endpoint-url=$LOCALSTACK_ENDPOINT secretsmanager create-secret \
  --name "cnpg/postgresql-cluster-app/uri" \
  --description "PostgreSQL connection URI" \
  --secret-string "postgresql://app:password@postgresql-cluster-rw:5432/appdb" \
  --region us-east-1 2>/dev/null || \
aws --endpoint-url=$LOCALSTACK_ENDPOINT secretsmanager update-secret \
  --secret-id "cnpg/postgresql-cluster-app/uri" \
  --secret-string "postgresql://app:password@postgresql-cluster-rw:5432/appdb" \
  --region us-east-1

aws --endpoint-url=$LOCALSTACK_ENDPOINT secretsmanager create-secret \
  --name "cnpg/postgresql-cluster-app/jdbc-uri" \
  --description "PostgreSQL JDBC URI" \
  --secret-string "jdbc:postgresql://postgresql-cluster-rw:5432/appdb" \
  --region us-east-1 2>/dev/null || \
aws --endpoint-url=$LOCALSTACK_ENDPOINT secretsmanager update-secret \
  --secret-id "cnpg/postgresql-cluster-app/jdbc-uri" \
  --secret-string "jdbc:postgresql://postgresql-cluster-rw:5432/appdb" \
  --region us-east-1

echo "✅ CNPG PostgreSQL secrets initialized successfully"