#!/usr/bin/env bash

# Regenerates docs/adr/README.md (the ADR index table) from individual ADR files.
# Parses: first heading (# ADR-NNN: Title) and **Status:** line from each file.
# Run as a pre-commit hook (pre-commit stage) so the index is always a build artifact.

set -o errexit
set -o pipefail

GREEN='\033[0;32m'
NC='\033[0m'

echo_info() { echo -e "${GREEN}INFO${NC} - $1"; }

ADR_DIR="docs/adr"
INDEX_FILE="${ADR_DIR}/README.md"

# Resolve repo root (script may be invoked from any directory)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
cd "${REPO_ROOT}"

if [[ ! -d "${ADR_DIR}" ]]; then
    echo_info "No ADR directory found at ${ADR_DIR} — skipping index generation"
    exit 0
fi

echo_info "Regenerating ADR index at ${INDEX_FILE}"

# Parse each ADR file and collect rows
declare -a rows=()

while IFS= read -r adr_file; do
    filename=$(basename "${adr_file}")

    # Extract number from filename (NNN-...).
    # Use sed to strip leading zeros before passing to printf to avoid octal issues.
    number=$(echo "${filename}" | grep -oE '^[0-9]+' | sed 's/^0*//' || echo "")
    [[ -z "$number" ]] && number="0"

    # Extract title from first heading line: # ADR-NNN: Title
    title=$(grep -m1 '^# ADR-' "${adr_file}" 2>/dev/null | sed 's/^# ADR-[0-9]*: //' || echo "")

    # Fall back: any first-level heading
    if [[ -z "${title}" ]]; then
        title=$(grep -m1 '^# ' "${adr_file}" 2>/dev/null | sed 's/^# //' || echo "(untitled)")
    fi

    # Extract status from **Status:** line
    status=$(grep -m1 '\*\*Status:\*\*' "${adr_file}" 2>/dev/null | sed 's/.*\*\*Status:\*\*[[:space:]]*//' | sed 's/[[:space:]]*$//' | tr -d '\r' || echo "Unknown")

    # Pad number for display
    display_num=$(printf "%03d" "${number}")

    rows+=("${display_num}|${title}|${status}|${filename}")
done < <(find "${ADR_DIR}" -maxdepth 1 -name '[0-9]*.md' | sort)

# Write index file
{
    echo "# Architecture Decision Records"
    echo ""
    echo "> Auto-generated index. Do not edit manually — regenerated by \`scripts/pre-commit/generate-adr-index.sh\`."
    echo ""
    echo "| # | Title | Status |"
    echo "|---|-------|--------|"

    for row in "${rows[@]}"; do
        IFS='|' read -r num title status fname <<< "${row}"
        echo "| ${num} | [${title}](${fname}) | ${status} |"
    done

    echo ""
    echo "## Adding a New ADR"
    echo ""
    echo "1. Create \`docs/adr/<NNN>-<short-title>.md\` following the existing format"
    echo "2. Set \`**Status:** Proposed\` initially"
    echo "3. This index regenerates automatically on commit"
    echo ""
    echo "## ADR Lifecycle"
    echo ""
    echo "ADRs are **append-only**. Never edit an accepted decision — supersede it with a new ADR that links back."
    echo ""
    echo "Statuses: \`Proposed\` → \`Accepted\` → \`Deprecated\` / \`Superseded by ADR-NNN\`"
} > "${INDEX_FILE}"

echo_info "✓ ADR index written (${#rows[@]} entries)"

# Stage the regenerated index so it's included in the current commit
git add "${INDEX_FILE}" 2>/dev/null || true
