# CloudNativePG Backup RBAC Configuration
# This file defines the necessary permissions for PostgreSQL cluster backups to access S3 credentials

# Role: Grants permission to access S3 credentials secret for backup operations
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgresql-cluster-backup-access
  namespace: cnpg-system
rules:
# Allow the PostgreSQL cluster to read the S3 credentials secret
# This is required for backup operations to authenticate with S3-compatible storage
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["postgresql-cluster-backup-s3-creds"]  # Specific secret containing S3 access credentials
  verbs: ["get", "list"]  # Read-only access to retrieve credentials
---
# RoleBinding: Connects the postgresql-cluster service account to the backup access role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgresql-cluster-backup-access
  namespace: cnpg-system
subjects:
# The service account used by the PostgreSQL cluster pods
- kind: ServiceAccount
  name: postgresql-cluster
  namespace: cnpg-system
roleRef:
  kind: Role
  name: postgresql-cluster-backup-access  # Reference to the role defined above
  apiGroup: rbac.authorization.k8s.io
