apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-externalsecret.yaml
  - traefik-externalsecret.yaml
  - redis-externalsecret.yaml
  - pgadmin4-externalsecret.yaml
  - n8n-externalsecret.yaml
  - temporal-externalsecret.yaml
  - loki-externalsecret.yaml