---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/base/cnpg
  prune: true
  wait: true
  timeout: 10m0s
  dependsOn:
    - name: traefik
    - name: localstack
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
