---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: database-workloads
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./database/base/workloads
  prune: true
  wait: true
  timeout: 15m0s
  dependsOn:
    - name: database-operators
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars