---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-services
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/services
  prune: true
  wait: true
  timeout: 8m0s
  dependsOn:
    - name: infrastructure-core
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars