apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-logging
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-monitoring  # Depends on monitoring stack (Grafana needs to be ready)
  interval: 1m
  retryInterval: 2m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./base/infrastructure/logging
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars