apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Resources ordered by dependency
resources:
  # Infrastructure layer first
  - infrastructure.yaml
  # Database layer second (depends on infrastructure)
  - database.yaml
  # Application layer last (depends on database)
  - apps.yaml
  # Services configuration
  - services

configMapGenerator:
  - name: cluster-vars
    envs:
      - environment.env
    options:
      disableNameSuffixHash: true
    namespace: flux-system
