apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Resources ordered by dependency
resources:
  # Infrastructure and foundational services first
  - ../apps/base/traefik
  - ../apps/base/localstack
  - ../apps/base/cnpg
  # Monitoring stack
  - ../apps/base/kube-prometheus-stack
  # Application services (depend on PostgreSQL)
  - ../apps/base/n8n
  - ../apps/base/temporal
  # Management tools
  - ../apps/base/weave-gitops
  - services

configMapGenerator:
  - name: cluster-vars
    envs:
      - environment.env
    options:
      disableNameSuffixHash: true
    namespace: flux-system
