apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Resources ordered by dependency
resources:
  # Infrastructure core (critical path: LocalStack + ESO)
  - infrastructure-core.yaml
  # Infrastructure services (parallel: Traefik, Monitoring, Weave GitOps)
  - infrastructure-services.yaml
  # Infrastructure config (ClusterSecretStore - needs core services running)
  - infrastructure-config.yaml
  # Database operators (depends on infrastructure config)
  - database-operators.yaml
  # Database workloads (depends on operators)
  - database-workloads.yaml
  # Application layer last (depends on database)
  - apps.yaml
  # Services configuration
  - services

configMapGenerator:
  - name: cluster-vars
    envs:
      - environment.env
    options:
      disableNameSuffixHash: true
    namespace: flux-system
