apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Resources ordered by dependency
resources:
  # Infrastructure and foundational services first
  - traefik.yaml
  - localstack.yaml
  - cnpg.yaml
  # Monitoring stack
  - kube-prometheus-stack.yaml
  # Application services (depend on PostgreSQL)
  - n8n.yaml
  - temporal.yaml
  # Management tools
  - weave-gitops.yaml
  - services

configMapGenerator:
  - name: cluster-vars
    envs:
      - environment.env
    options:
      disableNameSuffixHash: true
    namespace: flux-system
