apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Enterprise-grade FluxCD structure with optimized parallelization
# Components are organized in dependency waves for maximum efficiency

resources:
  # Wave 1: Infrastructure Core (Foundation - Sequential)
  - infrastructure-core.yaml
  
  # Wave 2: Infrastructure Operators (Depends on Core - Sequential)
  - infrastructure-operators.yaml
  
  # Wave 3: Infrastructure Configuration (Depends on Operators - Sequential)
  - infrastructure-config.yaml
  
  # Wave 4: Parallel Deployment (All depend on Config being ready)
  # These can deploy simultaneously for faster startup
  - infrastructure-monitoring.yaml  # Monitoring and GitOps tools
  - database-workloads.yaml        # Database services
  - services.yaml                  # Application services
  
  # Wave 5: Database UI (Depends on Database Workloads - Sequential)
  - database-ui.yaml

configMapGenerator:
  - name: cluster-vars
    envs:
      - environment.env
    options:
      disableNameSuffixHash: true
    namespace: flux-system
