---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: redisinsight
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/base/redisinsight
  prune: true
  wait: true
  timeout: 5m0s
  dependsOn:
    - name: redis
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars