---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: redis
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/base/redis
  prune: true
  wait: true
  timeout: 5m0s
  dependsOn:
    - name: external-secrets-operator
    - name: traefik
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars