---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: services
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./base/services
  prune: true
  wait: true
  timeout: 10m0s
  dependsOn:
    - name: infrastructure-config
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars