---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: temporal
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/base/temporal
  prune: true
  wait: true
  timeout: 10m0s
  dependsOn:
    - name: cloudnative-pg
    - name: traefik
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
