---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-user-auth
  namespace: weave-gitops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: localstack-secretstore
    kind: ClusterSecretStore
  target:
    name: cluster-user-auth
    creationPolicy: Owner
    template:
      data:
        username: "{{ .username }}"
        password: "{{ .passwordHash }}"
  dataFrom:
    - extract:
        key: weave-gitops/admin/credentials
