apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: localstack
  namespace: flux-system
spec:
  interval: 1m
  url: https://localstack.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: localstack
  namespace: flux-system
spec:
  targetNamespace: localstack
  interval: 1m
  chart:
    spec:
      chart: localstack
      version: 0.6.24
      sourceRef:
        kind: HelmRepository
        name: localstack
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # avoid localstack-localstack
    fullnameOverride: "localstack"

    # Minimal LocalStack configuration
    debug: true

    # Enable basic services
    services: "s3,sm,dynamodb,sqs,sns,lambda"

    # Service configuration
    service:
      type: ClusterIP
      port: 4566

    # Resource limits (important for Kubernetes stability)
    resources:
      limits:
        memory: "2Gi"
        cpu: "1000m"
      requests:
        memory: "1Gi"
        cpu: "500m"

    # Proper probe configuration format for LocalStack chart
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3

    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3
