apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: traefik-dashboard-credentials
  namespace: traefik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: localstack-secretstore
    kind: ClusterSecretStore
  target:
    name: traefik-dashboard-credentials
    creationPolicy: Owner
    template:
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        htpasswd: "{{ .htpasswd }}"
  data:
    - secretKey: username
      remoteRef:
        key: traefik/dashboard/credentials/username
    - secretKey: password
      remoteRef:
        key: traefik/dashboard/credentials/password
    - secretKey: htpasswd
      remoteRef:
        key: traefik/dashboard/credentials/htpasswd