apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - proxy-params.yaml
  - gateway.yaml
  - tracing-policy.yaml
  - referencegrant-otel.yaml
  - ../a2a
  - ../mcp
  - ../llm
